PACKAGE_NAME="surface-s2idle-fix"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="surface_s2idle_fix"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
